" vim plugins used. Note: This vimrc is using native VIM plugin manager
" .vim/pack/plugins/start
" ├── airline
" ├── ale
" ├── auto-pairs
" ├── rust.vim
" ├── unicode.vim
" ├── vagrantfile
" ├── vim-afterglow
" └── vim-airline-themes

set nocompatible
filetype plugin on
filetype indent on
syntax on

" no of spaces for tab
set tabstop=2

" no of spaces to be used while editing text. i.e <backspace> <tab>
set softtabstop=2

" no of spaces for autoindent
set shiftwidth=2

" convert tabs to spaces
set expandtab

" allow backspace to work in insert mode properly.
" indent => make backspace to work over autoindent
" eol => backspace will remove \n as well at the end of line
" start => delete text that you've inserted since insert mode started, and you can't delete any text that was previously inserted.'
set backspace=indent,eol,start

set path+=**

" commnd-line completions in vim
set wildmenu

" show line numbers
set number

" show commands being typed on the right bottom corner
set showcmd

" highlight the line at the cursor position
set cursorline
set cursorlineopt=line
" order of statements matter here
hi CursorLine ctermbg=235 cterm=none
hi CursorLine ctermfg=none cterm=none,bold

"Autocomplete uses dictionary if spell is set in the session. ie set spell
set complete+=kspell    

" highlight the searches and set the search highlight color more pleasing to eyes
set hlsearch
" order of statements matter here
hi Search ctermfg=none cterm=none
hi Search ctermbg=88 cterm=bold,underline

" Shows the mode of vim at the bottom of screen
set showmode

" set ruler. Position of cursor at the right bottom corner
set ruler

" Powerline settings: Not many colorschemes are available
" set rtp+=/Users/gpal/.vim/pack/plugins/opt/powerline/powerline/bindings/vim
" set laststatus=2

" Airline settings
set laststatus=2
" Need to install powerline-fonts and make sure terminal is also set to use one of powerline fonts. Otherwise you won't see fancy status in statusline
let g:airline_powerline_fonts=1
" Airline and Afterglow are working together here
let g:airline_theme='afterglow'

" make vimdiff output without colors
if &diff
  set t_Co=0
endif

" ALE settings
let g:ale_linters_explicit = 1
let g:ale_linters = {'javascript': ['eslint'],}
let g:ale_lint_on_save = 1
" clear background color in SignColumn for the following two
highlight clear ALEErrorSign
highlight clear ALEWarningSign
let g:ale_sign_error = '⛔'
let g:ale_sign_warning = '❕'
highlight SignColumn ctermbg=235 cterm=none
