require("mappings-config")
require("options-config")
require("plugins")
-- require("colorschemes-config.nightfox")
-- require("colorschemes-config.catppuccin")
-- require("colorschemes-config.onenord")
-- require("colorschemes-config.github")
-- require("colorschemes-config.rosepine")
-- require("colorschemes-config.tokyonight")
require("colorschemes-config.material")
-- require("colorschemes-config.vscode")
-- require("colorschemes-config.onedark")
-- require("colorschemes-config.gruvbox")
require("nvim-tree-config")
require("lsp-config.language-servers")
require("lsp-config.nvim-cmp")
-- require("lualine-config")
require("treesitter-config")
require("gitsigns-config")
require("diffview-config")
require("autopairs-config")
require("comment-config")
require("colorizer-config")
require("barbar-config")
require("floatterm-config")
require("telescope-config")
require("null-ls-config")
